engines:
  duplication:
    enabled: false
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - php
  eslint:
    enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.module"
  - "**.php"
exclude_paths:
- dist/**/*