language: php
php:
- 5.4
- hhvm

sudo: false

before_script: composer install

script:
- cd tests/setup/
- php install.php
- cd ../phpunit/
- composer update
- vendor/bin/phpunit --bootstrap bootstrap-dist.php opencart/admin
- vendor/bin/phpunit --bootstrap bootstrap-dist.php opencart/catalog
- vendor/bin/phpunit --bootstrap bootstrap-dist.php opencart/system
- php vendor/codeception/codeception/codecept run


notifications:
  slack:
    on_success: always
  email:
    recipients:
      - gerardo.ancha@gmail.com      
    on_success: never  # default: change
    on_failure: always # default: always
