language: php
php:
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1

before_script: composer install
script:
    - cp ${HOME}/xdebug.ini ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || return 0
    - phpunit -v
    - rm ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || return 0
    - if [ "$CHECKS" = "yes" ]; then composer sca; fi;
script:
- php test/setup/install.php
- cd tests/phpunit/
- composer update
- vendor/bin/phpunit --bootstrap bootstrap-dist.php opencart/admin
- vendor/bin/phpunit --bootstrap bootstrap-dist.php opencart/catalog
- vendor/bin/phpunit --bootstrap bootstrap-dist.php opencart/system

notifications:
  slack:
    on_success: always
  email:
    recipients:
      - gerardo.ancha@gmail.com      
    on_success: never  # default: change
    on_failure: always # default: always
