language: php
php:
- 5.4

dist: trusty
sudo: true

services:
  - mysql

os:
  - linux

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

before_install:
  - mysql -u root -e 'CREATE DATABASE opencart;'
  - mysql -u root opencart < opencart.sql
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xf phantomjs-2.1.1-linux-x86_64.tar.bz2
  - sudo rm -rf /usr/local/phantomjs
  - sudo mv phantomjs-2.1.1-linux-x86_64 /usr/local/phantomjs
  - sudo apt-get install ncftp
  #########
  - source .travis/travis.sh
  - if [[ $TRAVIS_PHP_VERSION != hhvm && $TRAVIS_PHP_VERSION != nightly && $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini; fi
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - travis_retry composer self-update


install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - mkdir -p build/logs
  - mv ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ${HOME}/xdebug.ini || return 0
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
  - if [ "$CHECKS" = "yes" ]; then travis_retry composer install-devtools; fi;
  - travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction $COMPOSER_FLAGS

cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/.php-cs-fixer


addons:
  sonarqube:
    organization: "testingucu2017-github"
    token:
      secure: "3a62d805f9521d93899e87be247d253c1fcb3107"
  sauce_connect:
    username: "testingucu.2017"
    access_key: "822c92b4-028e-4448-9507-0f13c1a1d720"
  code_climate:
    repo_token: "a9ad3982c8fd94a8f9f48b79c4738d13a397876e41db41e2e21ca1782a68512a"

before_script:
  - chmod +x upload-ftp.sh
  - bash upload-ftp.sh
  - npm install -g http-server
  - npm install -g pa11y
  - npm install -g pa11y-reporter-ci
  - php -S 127.0.0.1:8765 -t upload &
  - mkdir -p build/logs
  - touch build/logs/clover.xml
  ####
  - git config --global user.email ""
  - git config --global user.name "TestingUcu2017"
  - mkdir -p "$HOME/.php-cs-fixer"



  
script:
  - nvm install stable | nvm alias default stable | nvm use stable
  - jdk_switcher use oraclejdk8
  - find admin catalog tests -name *.php | xargs -n 1 -P4 php -l
#  - phpunit -c tests/phpunit/phpunit.xml # Estos test no corresponden.
# - phpunit --coverage-clover build/logs/clover.xml
  - sonar-scanner
  - php vendor/codeception/codeception/codecept run api
  - cd vaddy-master
  - nohup http-server -p 8080 >/dev/null 2>&1 & # seguridad
  - cd ..
  - cd pa11y-master
  - pa11y --threshold 40 open-cart.azurewebsites.net -s WCAG2AA
  - cd ..
  - mvn -f tests/ui-functional/pom.xml test
  - cp ${HOME}/xdebug.ini ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || return 0
  - rm ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || return 0
  - if [ "$CHECKS" = "yes" ]; then composer sca; fi;
  ##########
   - composer validate
   - if [[ $COVERAGE == yes ]]; then vendor/bin/phpunit --coverage-clover=build/logs/clover.xml; else vendor/bin/phpunit --no-coverage; fi
   - if [[ $EXECUTE_CS_CHECK == yes ]]; then php -n -d memory_limit=768M vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run; fi
  
after_success:
  - if [[ $COVERAGE == yes ]]; then php composer/bin/test-reporter; fi
  - vendor/bin/test-reporter


  


# Las credenciales fueron agregadas directamente en Travis CI -> Settings
deploy:
  provider: azure_web_apps
  username: "$open-cart"
  password: "b0v22TwzoPtv7ESsnfyT74xoFZZjPawpRbsuZ9kfd4jGBeaLE4q2wXT7xoXH"
  site: "open-cart"
  file: build/codeclimate-test-reporter.phar
  skip_cleanup: true 
  on:
   branch: release


   
notifications:
  slack:
    on_success: always
  email:
    recipients:
      - TestingUcu2017@gmail.com
    on_success: never  # default: change
    on_failure: always # default: always
