language: php
php:
- 5.4
- hhvm

services:
  - mysql

sudo: false

install:
- travis_retry composer install --no-interaction

script:
- composer validate --strict
- find admin catalog tests -name *.php | xargs -n 1 -P4 php -l
- vendor/bin/phpunit -c tests/phpunit.xml


notifications:
  slack:
    on_success: always
  email:
    recipients:
      - example@gmail.com      
    on_success: never  # default: change
    on_failure: always # default: always
