language: php
php:
- 5.4

dist: trusty
sudo: true

before_install:                  
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2                                                                                                                                                             
  - tar -xf phantomjs-2.1.1-linux-x86_64.tar.bz2                                                                                                                                                                                                
  - rm -rf /usr/local/phantomjs                                                                                                                                                                                                          
  - mv phantomjs-2.1.1-linux-x86_64 /usr/local/phantomjs

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - mkdir -p build/logs
  - mv ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ${HOME}/xdebug.ini || return 0
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
  - if [ "$CHECKS" = "yes" ]; then travis_retry composer install-devtools; fi;

cache:
    directories:
        - $HOME/.composer/cache


addons:
  sonarqube:
    organization: "testingucu2017-github"
    token:
      secure: "3a62d805f9521d93899e87be247d253c1fcb3107"


script:
  - nvm install stable | nvm alias default stable | nvm use stable
  - jdk_switcher use oraclejdk8
  - find admin catalog tests -name *.php | xargs -n 1 -P4 php -l
  - phpunit -c tests/phpunit/phpunit.xml
  - sonar-scanner
  - php vendor/codeception/codeception/codecept run api
  - mvn -f tests/ui-functional/pom.xml test
  - cp ${HOME}/xdebug.ini ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || return 0
  - phpunit -v
  - rm ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || return 0
  - if [ "$CHECKS" = "yes" ]; then composer sca; fi;

after_success:
  - bin/coveralls -v --exclude-no-stmt

# Las credenciales fueron agregadas directamente en Travis CI -> Settings
deploy:
  provider: azure_web_apps

notifications:
  slack:
    on_success: always
  email:
    recipients:
      - TestingUcu2017@gmail.com      
    on_success: never  # default: change
    on_failure: always # default: always





