language: php
php:
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1

before_script: composer install

script:
- cd tests/phpunit/
- composer update
- vendor/bin/phpunit --bootstrap bootstrap.php opencart/admin
- vendor/bin/phpunit --bootstrap bootstrap.php opencart/catalog
- vendor/bin/phpunit --bootstrap bootstrap.php opencart/system

notifications:
  slack:
    on_success: always
  email:
    recipients:
      - gerardo.ancha@gmail.com      
    on_success: never  # default: change
    on_failure: always # default: always
